# Generated by Django 4.2 on 2023-08-29 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                ("did", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=10)),
                ("sirname", models.TextField(max_length=10)),
                ("username", models.TextField(max_length=25)),
                ("email", models.EmailField(max_length=30)),
            ],
            options={"verbose_name_plural": "Details",},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("pid", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("add_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("image", models.URLField()),
                ("category", models.CharField(max_length=100)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.details"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Posts",},
        ),
    ]
